### ISSUE TITLE
Internal condition status doesnot update

### ISSUE THREAD

**Issue by palinf** [petertufvesson/ha-fsm#2]
On the code example: Condition A and Condition B are exact opposite therefore we can expect that they cannot be True same time.
The class fsm.Condition rely on callback based on the entity to change its internal state.
It seems that somehow, sometimes, the change is not propagated before the condition B for state B internal change is evaluated leading to a loop between  State A and State B.
The introduction of an unnecessary intermediate state (State I) is required to avoid this loop. 

```
      State(id='IDLE', enter_programs=[self.besoin_chaleur], transitions=[ #State A
        Transition(next='CHAUFFAGE1', conditions=[
          Condition(entity='binary_sensor.spa_besoin_chaleur', operand='on'), #Condition A
        ]),
      ]
      ),

      State(id='CHAUFFAGE1', transitions=[ #State I
        Transition(next='CHAUFFAGE2', conditions=[
          Condition(timeout_time=1),
        ]),
      ]
      ),

      State(id='CHAUFFAGE2', enter_programs=[self.chauffage], transitions=[ #State B
        Transition(next='MAINTIEN_TEMP', conditions=[
          Condition(entity='binary_sensor.spa_besoin_chaleur', operator=Neq, operand='on'), #Condition B
        ]),
      ]
      ),
```

**Comment by petertufvesson** [comment]
It has been a while and some updates never got pushed to github. I have also seen this problem, and it is kind of hard to get rid of as a single entity change can start a snow-ball effect with multiple state changes. Since there is no natural "clock" in the system (everything is event driven) the FSM is closer to a Meely-machine than a Moore-machine.
Never the less,  please try the new code I just pushed. I find this more stable.
If you still experience the same problem, please let me know.
Oh, and I did not have time to update the example in the README. The syntax is similar though.
